const path = require('node:path');

const appEntries = [
  // Core
  './Aurora.Sira.Web/wwwroot/assets/js/bundle/core.dev.js',
  // App
  './Aurora.Sira.Web/wwwroot/assets/js/rutas/layout-routing.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/transversal/constantes.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/transversal/funciones.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/bandejaFichas/bandejaFichas.js',
  './Aurora.Sira.Web/wwwroot/assets/js/app/sesionUsuario/sesionUsuario.js',
  // Fichas - Modulo CEM - Sección A
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionA/contenido/contenido.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionA/preguntas1/preguntas1.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionA/preguntas2/preguntas2.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionA/preguntas3/preguntas3.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionA/preguntas4/preguntas4.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionA/preguntas5/preguntas5.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionA/preguntas6/preguntas6.js',
  // Fichas - Modulo CEM - Sección B
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionB/contenido/contenido.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionB/preguntas1/preguntas1.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionB/preguntas2/preguntas2.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionB/preguntas3/preguntas3.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionB/preguntas4/preguntas4.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionB/preguntas5/preguntas5.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionB/preguntas6/preguntas6.js',
  // Fichas - Modulo CEM - Sección C
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionC/contenido/contenido.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionC/preguntas1/preguntas1.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionC/preguntas2/preguntas2.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionC/preguntas3/preguntas3.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionC/preguntas4/preguntas4.js',
  // Fichas - Modulo CEM - Sección D
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionD/contenido/contenido.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionD/preguntas1/preguntas1.js',
  // Fichas - Modulo CEM - Sección E
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionE/contenido/contenido.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionE/preguntas1/preguntas1.js',
  // Fichas - Modulo CEM - Sección F
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionF/contenido/contenido.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionF/preguntas1/preguntas1.js',
  // Fichas - Modulo CEM - Sección G
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionG/contenido/contenido.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionG/preguntas1/preguntas1.js',
  // Fichas - Modulo CEM - Sección H
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionH/contenido/contenido.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/seccionH/preguntas1/preguntas1.js',
  // Bandeja Fichas - Modulo CEM
  './Aurora.Sira.Cem.Web/wwwroot/js/bandejaFichasDerivar/bandejaFichasDerivar.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/bandejaFichasDerivar/modalDerivar.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/bandejaFichasRecepcion/bandejaFichasRecepcion.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/bandejaFichasRecepcion/modalRecepcionar.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/bandejaFichasConsultaHistorico/bandejaFichasConsultaHistorico.js',
  // Fichas - Modulo CEM
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/contenido/contenido.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/contenido/modalExtender.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/contenido/modalGenerarCorrelativo.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/ficha/contenido/modalHistorial.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/importacion/importacion.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/exportar/exportar.js',
  './Aurora.Sira.Cem.Web/wwwroot/js/bandejaFichas/modalSustentoAnulacion.js',
  // Fichas - Modulo IFHD
  './Aurora.IFHD/Aurora.Sira.IFHD.Web/wwwroot/js/transversal/constantes.js',
  './Aurora.IFHD/Aurora.Sira.IFHD.Web/wwwroot/js/bandejaFichas/bandejaFichas.js',
  './Aurora.IFHD/Aurora.Sira.IFHD.Web/wwwroot/js/ficha/contenido/contenido.js',
  './Aurora.IFHD/Aurora.Sira.IFHD.Web/wwwroot/js/ficha/seccionA/contenido/contenido.js',
  './Aurora.IFHD/Aurora.Sira.IFHD.Web/wwwroot/js/ficha/seccionA/preguntas1/preguntas1.js',
  './Aurora.IFHD/Aurora.Sira.IFHD.Web/wwwroot/js/bandejaFichasConsultaHistorico/bandejaFichasConsultaHistorico.js',
  './Aurora.IFHD/Aurora.Sira.IFHD.Web/wwwroot/js/ficha/seccionB/contenido/contenido.js',
  './Aurora.IFHD/Aurora.Sira.IFHD.Web/wwwroot/js/ficha/seccionB/preguntas1/preguntas1.js',
  // Fichas - Modulo HRT
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/transversal/constantes.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/transversal/funciones.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/bandejaFichas/bandejaFichas.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/ficha/contenido/modalAnexosAsociados.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/ficha/contenido/contenido.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/ficha/seccionA/contenido/contenido.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/ficha/seccionA/preguntas1/preguntas1.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/ficha/seccionA/preguntas2/preguntas2.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/ficha/seccionA/preguntas3/preguntas3.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/ficha/seccionB/contenido/contenido.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/ficha/seccionB/preguntas1/preguntas1.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/ficha/seccionB/preguntas2/preguntas2.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/ficha/seccionB/preguntas3/preguntas3.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/ficha/seccionC/contenido/contenido.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/ficha/seccionC/preguntas1/preguntas1.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/ficha/seccionD/contenido/contenido.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/ficha/seccionD/preguntas1/preguntas1.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/ficha/seccionD/preguntas2/preguntas2.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/ficha/seccionE/contenido/contenido.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/ficha/seccionE/preguntas1/preguntas1.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/ficha/seccionF/contenido/contenido.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/ficha/seccionF/preguntas1/preguntas1.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/bandejaFichasConsultaHistorico/bandejaFichasConsultaHistorico.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/fichaAnexo2/contenido/contenido.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/fichaAnexo2/seccionA/contenido/contenido.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/fichaAnexo2/seccionA/preguntas3/preguntas3.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/fichaAnexo2/seccionB/contenido/contenido.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/fichaAnexo2/seccionB/preguntas2/preguntas2.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/fichaAnexo2/seccionB/preguntas3/preguntas3.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/fichaAnexo2/seccionC/contenido/contenido.js',
  './Aurora.HRT/Aurora.Sira.HRT.Web/wwwroot/js/fichaAnexo2/seccionC/preguntas1/preguntas1.js',
  // Fichas - Modulo Empoderamiento
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/transversal/constantes.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/transversal/funciones.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/bandejaFichas/bandejaFichas.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/contenido/modalAnexosAsociados.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/contenido/contenido.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionA/contenido/contenido.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionA/preguntas1/preguntas1.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionB/contenido/contenido.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionB/preguntas1/preguntas1.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionC/contenido/contenido.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionC/preguntas1/preguntas1.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionD/contenido/contenido.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionD/preguntas1/preguntas1.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionE/contenido/contenido.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionE/preguntas1/preguntas1.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionF/contenido/contenido.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionF/preguntas1/preguntas1.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionG/contenido/contenido.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionG/preguntas1/preguntas1.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionH/contenido/contenido.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionH/preguntas1/preguntas1.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionH/preguntas2/preguntas2.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionI/contenido/contenido.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionI/preguntas1/preguntas1.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionJ/contenido/contenido.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/ficha/seccionJ/preguntas1/preguntas1.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/fichaAnexo2/contenido/contenido.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/fichaAnexo2/seccionA/contenido/contenido.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/fichaAnexo2/seccionA/preguntas1/preguntas1.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/importacion/importacion.js',
  './Aurora.EMP/Aurora.Sira.EMP.Web/wwwroot/js/exportar/exportar.js',
];

module.exports = {
  entry: {
    app: appEntries,
    // core: './Aurora.Sira.Web/wwwroot/assets/js/bundle/core.dev.js',
  },
  output: {
    filename: '[name].bundle.js',
    path: path.resolve(__dirname, 'Aurora.Sira.Web/wwwroot/assets/js/bundle'),
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: 'babel-loader',
      },
    ],
  },
}
